workflows:
  apk_release:
    name: Currículo Pro-R - APK Release
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Instalando dependências
        script: flutter pub get
      - name: Gerando APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk